name: Build and Release

on:
  push:
    tags: [ 'v*' ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      matrix:
        go-version: [ '1.23.x' ]
        os: [ windows, linux, darwin ]
        arch: [ amd64, arm64 ]
        exclude:
          - os: darwin
            arch: arm64
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
          cache: false  # 禁用 setup-go 的自动缓存

#      # 🔥 新增缓存步骤（放在 `go mod tidy` 之前）
#      - name: Cache Go modules
#        uses: actions/cache@v4
#        with:
#          path: ~/go/pkg/mod
#          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
#          restore-keys: |
#            ${{ runner.os }}-go-

      - name: Install dependencies
        run: go mod tidy

      - name: Get version from code
        id: version
        run: |
          VERSION=$(grep -E 'appVersion\s+=' remotec.go | awk -F'"' '{print $2}')
          echo "version=${VERSION}" >> $GITHUB_OUTPUT

      - name: Build
        run: |
          OUTPUT="remotec"
          if [ "${{ matrix.os }}" = "windows" ]; then
            OUTPUT="$OUTPUT.exe"
          fi
          CGO_ENABLED=0 GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build -o $OUTPUT
          echo "Built $OUTPUT"

      - name: Create archives
        run: |
          mkdir -p dist
          if [ "${{ matrix.os }}" = "windows" ]; then
            zip "dist/remotec-${{ steps.version.outputs.version }}-windows-${{ matrix.arch }}.zip" "remotec.exe"
          elif [ "${{ matrix.os }}" = "darwin" ]; then
            tar -czf "dist/remotec-${{ steps.version.outputs.version }}-macos-${{ matrix.arch }}.tar.gz" "remotec"
          else
            tar -czf "dist/remotec-${{ steps.version.outputs.version }}-linux-${{ matrix.arch }}.tar.gz" "remotec"
          fi

#      - name: Upload artifacts
#        uses: actions/upload-artifact@v4
#        with:
#          name: remotec-binaries-${{ matrix.os }}-${{ matrix.arch }}  # 唯一名称
#          path: dist/
#          if-no-files-found: error
          
      - name: Create Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            dist/*.zip
            dist/*.tar.gz
          generate_release_notes: true
          