name: Build and Release

on:
  push:
    tags: [ 'v*' ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      matrix:
        go-version: [ '1.23.x' ]
        # 并行构建的矩阵组合
        os: [linux, windows, darwin]
        arch: [amd64, arm64, arm, mips, mipsle]
        # 排除无效组合
        exclude:
          - os: windows
            arch: arm
          - os: windows
            arch: mips
          - os: windows
            arch: mipsle
          - os: darwin
            arch: arm
          - os: darwin
            arch: mips
          - os: darwin
            arch: mipsle
        # 为特定组合添加额外参数（如 GOARM）
        include:
          - os: linux
            arch: arm
            goarm: 7
            suffix: linux-armv7  # 显式命名 ARMv7
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install dependencies
        run: go mod tidy

      - name: Get version
        id: version
        run: |
          VERSION=$(grep -E '^version:' config.yml | awk -F': ' '{print $2}')
          echo "version=${VERSION}" >> $GITHUB_OUTPUT

      - name: Build
        run: |
          OUTPUT="remotec"
          if [ "${{ matrix.os }}" = "windows" ]; then
            OUTPUT="$OUTPUT.exe"
          fi
          # 动态设置 GOARM（仅限 ARMv7）
          if [ "${{ matrix.arch }}" = "arm" ] && [ -n "${{ matrix.goarm }}" ]; then
            export GOARM=${{ matrix.goarm }}
          fi
          CGO_ENABLED=0 GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build -o $OUTPUT
          echo "Built $OUTPUT for ${{ matrix.os }}-${{ matrix.arch }}"

      - name: Generate release suffix
        id: suffix
        run: |
          if [ -n "${{ matrix.suffix }}" ]; then
            SUFFIX="${{ matrix.suffix }}"
          else
            SUFFIX="${{ matrix.os }}-${{ matrix.arch }}"
          fi
          echo "suffix=${SUFFIX}" >> $GITHUB_OUTPUT

      - name: Create archives
        run: |
          mkdir -p dist
          if [ "${{ matrix.os }}" = "windows" ]; then
            zip "dist/remotec-${{ steps.version.outputs.version }}-${{ steps.suffix.outputs.suffix }}.zip" "remotec.exe"
          else
            tar -czf "dist/remotec-${{ steps.version.outputs.version }}-${{ steps.suffix.outputs.suffix }}.tar.gz" "remotec"
          fi

      - name: Create Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            dist/*.zip
            dist/*.tar.gz
          generate_release_notes: true