name: Build and Release

on:
  push:
    tags: [ 'v*' ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      matrix:
        go-version: [ '1.23.x' ]
        # 精简后的架构组合：优先覆盖主流设备
        include:
          - os: linux
            arch: amd64
            suffix: linux-amd64
          - os: linux
            arch: arm
            goarm: 7
            suffix: linux-armv7
          - os: linux
            arch: arm64
            suffix: linux-arm64
          - os: linux
            arch: mips
            suffix: linux-mips
          - os: linux
            arch: mipsle
            suffix: linux-mipsle
          - os: windows
            arch: amd64
            suffix: windows-amd64
          - os: windows
            arch: arm64
            suffix: windows-arm64
          - os: darwin
            arch: amd64
            suffix: macos-amd64
          - os: darwin
            arch: arm64
            suffix: macos-arm64
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install dependencies
        run: go mod tidy

      - name: Get version
        id: version
        run: |
          VERSION=$(grep -E '^version:' config.yml | awk -F': ' '{print $2}')
          echo "version=${VERSION}" >> $GITHUB_OUTPUT

      - name: Build
        run: |
          OUTPUT="remotec"
          if [ "${{ matrix.os }}" = "windows" ]; then
            OUTPUT="$OUTPUT.exe"
          fi
          # 动态设置 GOARM（仅限 ARMv7）
          if [ "${{ matrix.arch }}" = "arm" ] && [ -n "${{ matrix.goarm }}" ]; then
            export GOARM=${{ matrix.goarm }}
          fi
          CGO_ENABLED=0 GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build -o $OUTPUT
          echo "Built $OUTPUT for ${{ matrix.os }}-${{ matrix.arch }}"

      - name: Create archives
        run: |
          mkdir -p dist
          if [ "${{ matrix.os }}" = "windows" ]; then
            zip "dist/remotec-${{ steps.version.outputs.version }}-${{ matrix.suffix }}.zip" "remotec.exe"
          else
            tar -czf "dist/remotec-${{ steps.version.outputs.version }}-${{ matrix.suffix }}.tar.gz" "remotec"
          fi

      - name: Create Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            dist/*.zip
            dist/*.tar.gz
          generate_release_notes: true